---
title: "Ryan Reisinger"
---

I am an Associate Professor in marine ecology at the [School of Ocean and Earth Science](https://www.southampton.ac.uk/about/faculties-schools-departments/school-of-ocean-and-earth-science), [University of Southampton](https://www.southampton.ac.uk/).

My work broadly focuses on the ecology of marine predators.

I look at how the biophysical oceanographic environment and anthropogenic factors influence the behaviour of marine predators and how we can model and forecast various aspects of their ecology in our changing seascapes. While my work has a strong fundamental ecology axis, I am increasingly working on the applied and broader implications of this work – how do we use information about predators for marine conservation and management and to understand broader ecosystem pattern, process and status?  To do this I use both field- and desk-based studies and methods including animal biologging, remote-sensing and stable isotope analysis. I analyse the resulting data with modern, highly quantitative tools like machine learning and network analysis.
