---
title: "Selected presentations"
---

Below you will find resources (such as citations and extended notes) for selected talks and posters.

## Latest/upcoming

- 5 October 2026\
  **Impact of Arctic shipping on whales.** *Arctic Shipping: A Critical Perspective, presented by the Institute of Maritime Law (University of Southampton) and Gard*. International Chamber of Shipping Maritime Hub, London, UK.\
  [Sources and references](/talks_pages/2026-10-05.qmd)

## 2025

- January 2025\
  **Roaming Giants.** *Ocean Giants: Whales and the Worlds They Shape. Winchester Cathedral, Winchester, UK.*\
  [Our campanion piece in The Conversation](https://theconversation.com/art-music-and-science-combine-at-a-new-whale-exhibition-at-winchester-cathedral-248024) \| [University of Southampton's news story](https://www.southampton.ac.uk/news/2025/02/science-and-art-combine-for-thoughtprovoking-event-under-the-whales.page) \| [University of Southampton's YouTube](https://youtu.be/BUExvxtdcOc?si=f-Zl0LThpkTkjEGy) \| [Coverage in the Hampshire Chronicle](https://www.hampshirechronicle.co.uk/news/24917728.winchester-cathedral-university-southampton-host-whale-event/) \| [Coverage in the Southern Daily Echo](https://www.dailyecho.co.uk/news/24918097.southampton-scientists-take-part-sperm-whale-exhibition/)

## 2022

- August 2022\
  **Predator-derived bioregions in the Southern Ocean: characteristics, drivers and representation in Marine Protected Areas.** *10th SCAR Open Science Conference, 1–10 August 2022*. Virtual meeting hosted in Vasco da Gama, India\
  [Watch the talk recording on Youtube](https://youtu.be/IcmPkE53EUw?t=4927)
