---
title: "Impact of Arctic shipping on whales"
---

5 October 2026

*Arctic Shipping: A Critical Perspective, presented by the Institute of Maritime Law (University of Southampton) and Gard*. International Chamber of Shipping Maritime Hub, London, UK

[← Back to all presentation resources](../presentations.qmd)

## References

### Why whales matter

R. Chami et al. (2019) "Nature's solution to climate change". *Finance & Development* (International Monetary Fund). Available at: <https://www.imf.org/en/publications/fandd/issues/2019/12/natures-solution-to-climate-change-chami>

Roman, J. et al. (2014) Whales as ecosystem engineers. Frontiers in Ecology and the Environment. <https://doi.org/10.1890/130220>

### Arctic context

WWF Global Arctic Programme (2024) *Arctic Blue Corridors: Safeguarding migrating whales from pressures for a connected Arctic Ocean*. WWF. <https://www.arcticwwf.org/newsroom/reports/online-report-arctic-blue-corridors/>

Yi, W., Liu, H., Peng, L. *et al.* Drivers and environmental impacts of Arctic shipping. *Nat Rev Earth Environ* **7**, 343–358 (2026). <https://doi.org/10.1038/s43017-026-00790-2>

### Ocean noise and vessel strike

Carlos M. Duarte *et al.*The soundscape of the Anthropocene ocean.*Science***371**,eaba4658(2021).DOI:[10.1126/science.aba4658](https://doi.org/10.1126/science.aba4658)

A. C. Nisi, et al. Ship collision risk threatens whales across the world’s oceans. Science **386**, 870–875 (2024). [**CrossRef**](https://www.biorxiv.org/lookup/external-ref?access_num=10.1126/science.adp1950&link_type=DOI) [**PubMed**](https://www.biorxiv.org/lookup/external-ref?access_num=39571007&link_type=MED&atom=%2Fbiorxiv%2Fearly%2F2025%2F09%2F29%2F2025.09.26.678754.atom)[**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=A.%20C.+Nisi&author%5B1%5D=H.+Welch&author%5B2%5D=S.+Brodie&author%5B3%5D=C.+Leiphardt&author%5B4%5D=R.+Rhodes&author%5B5%5D=E.%20L.+Hazen&author%5B6%5D=J.%20V.+Redfern&author%5B7%5D=T.%20A.+Branch&author%5B8%5D=A.%20S.+Barreto&author%5B9%5D=J.+Calambokidis&author%5B10%5D=T.+Clavelle&author%5B11%5D=L.+Dares&author%5B12%5D=A.+de%20Vos&author%5B13%5D=S.+Gero&author%5B14%5D=J.%20A.+Jackson&author%5B15%5D=R.%20D.+Kenney&author%5B16%5D=D.+Kroodsma&author%5B17%5D=R.+Leaper&author%5B18%5D=D.%20J.+McCauley&author%5B19%5D=S.%20E.+Moore&author%5B20%5D=E.+Ovsyanikova&author%5B21%5D=S.+Panigada&author%5B22%5D=C.%20V.+Robinson&author%5B23%5D=T.+White&author%5B24%5D=J.+Wilson&author%5B25%5D=B.+Abrahms&title=Ship+collision+risk+threatens+whales+across+the+world%E2%80%99s+oceans&publication_year=2024&journal=Science&volume=386&pages=870-875)

F. C. Womersley, et al. Global collision-risk hotspots of marine traffic and the world’s largest fish, the whale shark. Proc. Natl. Acad. Sci. **119**, e2117440119 (2022). [**CrossRef**](https://www.biorxiv.org/lookup/external-ref?access_num=10.1073/pnas.2117440119&link_type=DOI) [**PubMed**](https://www.biorxiv.org/lookup/external-ref?access_num=35533277&link_type=MED&atom=%2Fbiorxiv%2Fearly%2F2025%2F09%2F29%2F2025.09.26.678754.atom)[**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=F.%20C.+Womersley&author%5B1%5D=N.%20E.+Humphries&author%5B2%5D=N.+Queiroz&author%5B3%5D=M.+Vedor&author%5B4%5D=I.+da%20Costa&author%5B5%5D=M.+Furtado&author%5B6%5D=J.%20P.+Tyminski&author%5B7%5D=K.+Abrantes&author%5B8%5D=G.+Araujo&author%5B9%5D=S.%20S.+Bach&author%5B10%5D=A.+Barnett&author%5B11%5D=M.%20L.+Berumen&author%5B12%5D=S.+Bessudo%20Lion&author%5B13%5D=C.%20D.+Braun&author%5B14%5D=E.+Clingham&author%5B15%5D=J.%20E.%20M.+Cochran&author%5B16%5D=R.+de%20la%20Parra&author%5B17%5D=S.+Diamant&author%5B18%5D=A.%20D.%20M.+Dove&author%5B19%5D=C.%20L.+Dudgeon&author%5B20%5D=M.%20V.+Erdmann&author%5B21%5D=E.+Espinoza&author%5B22%5D=R.+Fitzpatrick&author%5B23%5D=J.%20G.+Cano&author%5B24%5D=J.%20R.+Green&author%5B25%5D=H.%20M.+Guzman&author%5B26%5D=R.+Hardenstine&author%5B27%5D=A.+Hasan&author%5B28%5D=F.%20H.%20V.+Hazin&author%5B29%5D=A.%20R.+Hearn&author%5B30%5D=R.%20E.+Hueter&author%5B31%5D=M.%20Y.+Jaidah&author%5B32%5D=J.+Labaja&author%5B33%5D=F.+Ladino&author%5B34%5D=B.%20C.%20L.+Macena&author%5B35%5D=J.%20J.+Morris&author%5B36%5D=B.%20M.+Norman&author%5B37%5D=C.+Pe%C3%B1aherrera-Palma&author%5B38%5D=S.%20J.+Pierce&author%5B39%5D=L.%20M.+Quintero&author%5B40%5D=D.+Ram%C3%ADrez-Mac%C3%ADas&author%5B41%5D=S.%20D.+Reynolds&author%5B42%5D=A.%20J.+Richardson&author%5B43%5D=D.%20P.+Robinson&author%5B44%5D=C.%20A.+Rohner&author%5B45%5D=D.%20R.%20L.+Rowat&author%5B46%5D=M.+Sheaves&author%5B47%5D=M.%20S.+Shivji&author%5B48%5D=A.%20B.+Sianipar&author%5B49%5D=G.%20B.+Skomal&author%5B50%5D=G.+Soler&author%5B51%5D=I.+Syakurachman&author%5B52%5D=S.%20R.+Thorrold&author%5B53%5D=D.%20H.+Webb&author%5B54%5D=B.%20M.+Wetherbee&author%5B55%5D=T.%20D.+White&author%5B56%5D=T.+Clavelle&author%5B57%5D=D.%20A.+Kroodsma&author%5B58%5D=M.+Thums&author%5B59%5D=L.%20C.+Ferreira&author%5B60%5D=M.%20G.+Meekan&author%5B61%5D=L.%20M.+Arrowsmith&author%5B62%5D=E.%20K.+Lester&author%5B63%5D=M.%20M.+Meyers&author%5B64%5D=L.%20R.+Peel&author%5B65%5D=A.%20M.%20M.+Sequeira&author%5B66%5D=V.%20M.+Egu%C3%ADluz&author%5B67%5D=C.%20M.+Duarte&author%5B68%5D=D.%20W.+Sims&title=Global+collision-risk+hotspots+of+marine+traffic+and+the+world%E2%80%99s+largest+fish,+the+whale+shark&publication_year=2022&journal=Proc.+Natl.+Acad.+Sci&volume=119)

### Mitigation

C. R. Findlay, et al. Small reductions in cargo vessel speed substantially reduce noise impacts to marine mammals. Sci. Adv. **9**, eadf2987 (2023). [**PubMed**](https://www.biorxiv.org/lookup/external-ref?access_num=37343089&link_type=MED&atom=%2Fbiorxiv%2Fearly%2F2025%2F09%2F29%2F2025.09.26.678754.atom) [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=C.%20R.+Findlay&author%5B1%5D=L.+Rojano-Do%C3%B1ate&author%5B2%5D=J.+Tougaard&author%5B3%5D=M.%20P.+Johnson&author%5B4%5D=P.%20T.+Madsen&title=Small+reductions+in+cargo+vessel+speed+substantially+reduce+noise+impacts+to+marine+mammals&publication_year=2023&journal=Sci.+Adv&volume=9)

R. Leaper. The Role of Slower Vessel Speeds in Reducing Greenhouse Gas Emissions, Underwater Noise and Collision Risk to Whales. Front. Mar. Sci. **6** (2019). [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=R.+Leaper&title=The+Role+of+Slower+Vessel+Speeds+in+Reducing+Greenhouse+Gas+Emissions&publication_year=2019&journal=Underwater+Noise+and+Collision+Risk+to+Whales.+Front.+Mar.+Sci&volume=6)

R. P. Schoeman, et al. A Global Review of Vessel Collisions With Marine Animals. Front. Mar. Sci. **7**, 292 (2020). [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=R.%20P.+Schoeman&author%5B1%5D=C.+Patterson-Abrolat&author%5B2%5D=S.+Pl%C3%B6n&title=A+Global+Review+of+Vessel+Collisions+With+Marine+Animals&publication_year=2020&journal=Front.+Mar.+Sci&volume=7)

M. Sèbe, et al. Reducing whale-ship collisions by better estimating damages to ships. Sci. Total Environ. **713**, 136643 (2020). [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=M.+S%C3%A8be&author%5B1%5D=C.%20A.+Kontovas&author%5B2%5D=L.+Pendleton&title=Reducing+whale-ship+collisions+by+better+estimating+damages+to+ships&publication_year=2020&journal=Sci.+Total+Environ&volume=713)

### Voyage optimisation

P. A. Grudniewski, A. J. Sobey. Coevolutionary strategies at the collective level for improved generalism. Data-Centric Eng. **4**, e6 (2023). [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=P.%20A.+Grudniewski&author%5B1%5D=A.%20J.+Sobey&title=Coevolutionary+strategies+at+the+collective+level+for+improved+generalism&publication_year=2023&journal=Data-Centric+Eng&volume=4)

Ryan R. Reisinger, Przemyslaw A. Grudniewski, Freya C. Womersley, David W. Sims, Adam J. Sobey (2025) Optimising voyages for biodiversity: rerouting vessels around ocean giants can have minimal impact on shipping. bioRxiv 2025.09.26.678754; doi: <https://doi.org/10.1101/2025.09.26.678754>

Theyr. *Theyr T-VOS* \[Software\]. Available at: <https://theyr.net>

F. C. Womersley, et al. Climate-driven global redistribution of an ocean giant predicts increased threat from shipping. *Nat*. Clim. Change, 1–10 (2024). [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=F.%20C.+Womersley&author%5B1%5D=L.%20L.+Sousa&author%5B2%5D=N.%20E.+Humphries&author%5B3%5D=K.+Abrantes&author%5B4%5D=G.+Araujo&author%5B5%5D=S.%20S.+Bach&author%5B6%5D=A.+Barnett&author%5B7%5D=M.%20L.+Berumen&author%5B8%5D=S.%20B.+Lion&author%5B9%5D=C.%20D.+Braun&author%5B10%5D=E.+Clingham&author%5B11%5D=J.%20E.%20M.+Cochran&author%5B12%5D=R.+de%20la%20Parra&author%5B13%5D=S.+Diamant&author%5B14%5D=A.%20D.%20M.+Dove&author%5B15%5D=C.%20M.+Duarte&author%5B16%5D=C.%20L.+Dudgeon&author%5B17%5D=M.%20V.+Erdmann&author%5B18%5D=E.+Espinoza&author%5B19%5D=L.%20C.+Ferreira&author%5B20%5D=R.+Fitzpatrick&author%5B21%5D=J.%20G.+Cano&author%5B22%5D=J.%20R.+Green&author%5B23%5D=H.%20M.+Guzman&author%5B24%5D=R.+Hardenstine&author%5B25%5D=A.+Hasan&author%5B26%5D=F.%20H.%20V.+Hazin&author%5B27%5D=A.%20R.+Hearn&author%5B28%5D=R.%20E.+Hueter&author%5B29%5D=M.%20Y.+Jaidah&author%5B30%5D=J.+Labaja&author%5B31%5D=F.+Ladino&author%5B32%5D=B.%20C.%20L.+Macena&author%5B33%5D=M.%20G.+Meekan&author%5B34%5D=J.%20J.+Morris&author%5B35%5D=B.%20M.+Norman&author%5B36%5D=C.%20R.+Pe%C3%B1aherrera-Palma&author%5B37%5D=S.%20J.+Pierce&author%5B38%5D=L.%20M.+Quintero&author%5B39%5D=D.+Ram%C3%ADrez-Mac%C3%ADas&author%5B40%5D=S.%20D.+Reynolds&author%5B41%5D=D.%20P.+Robinson&author%5B42%5D=C.%20A.+Rohner&author%5B43%5D=D.%20R.%20L.+Rowat&author%5B44%5D=A.%20M.%20M.+Sequeira&author%5B45%5D=M.+Sheaves&author%5B46%5D=M.%20S.+Shivji&author%5B47%5D=A.%20B.+Sianipar&author%5B48%5D=G.%20B.+Skomal&author%5B49%5D=G.+Soler&author%5B50%5D=I.+Syakurachman&author%5B51%5D=S.%20R.+Thorrold&author%5B52%5D=M.+Thums&author%5B53%5D=J.%20P.+Tyminski&author%5B54%5D=D.%20H.+Webb&author%5B55%5D=B.%20M.+Wetherbee&author%5B56%5D=N.+Queiroz&author%5B57%5D=D.%20W.+Sims&title=Climate-driven+global+redistribution+of+an+ocean+giant+predicts+increased+threat+from+shipping.+Nat&publication_year=2024&journal=Clim.+Change&pages=1-10)

S. Yuen, et al. “The effect of epigenetic blocking on dynamic multi-objective optimisation problems” in Proceedings of the Genetic and Evolutionary Computation Conference Companion (Association for Computing Machinery, New York, NY, USA, 2022; doi:10.1145/3520304.3529022)GECCO’ **22**, pp. 379–382. [**CrossRef**](https://www.biorxiv.org/lookup/external-ref?access_num=10.1145/3520304.3529022&link_type=DOI)

### Policy and action

C. Nathan (2026) *"Call for dynamic regulation of our oceans to reduce whale strikes"*. The Alan Turing Institute. Available at: <https://www.turing.ac.uk/news/call-dynamic-regulation-our-oceans-reduce-whale-strikes>

International Maritime Organization (IMO). *International Code for Ships Operating in Polar Waters (Polar Code)*. <https://www.imo.org/en/ourwork/safety/pages/polar-code.aspx>

International Maritime Organization (IMO) (2023) *Revised guidelines for the reduction of underwater radiated noise from shipping to address adverse impacts on marine life*. MEPC.1/Circ.906, 22 August 2023. London: IMO. <https://wwwcdn.imo.org/localresources/en/Documents/MEPC.1-Circ.906%20-%20Revised%20Guidelines%20For%20The%20Reduction%20Of%20Underwater%20Radiated%20NoiseFrom%20Shipping%20To%20Address...%20(Secretariat).pdf>

F. C. Womersley, et al. Four steps to curb ‘ocean roadkill.’ Nature **621**, 34–38 (2023). [**PubMed**](https://www.biorxiv.org/lookup/external-ref?access_num=37673985&link_type=MED&atom=%2Fbiorxiv%2Fearly%2F2025%2F09%2F29%2F2025.09.26.678754.atom) [**Google Scholar**](https://www.biorxiv.org/lookup/google-scholar?link_type=googlescholar&gs_type=article&author%5B0%5D=F.%20C.+Womersley&author%5B1%5D=A.+Loveridge&author%5B2%5D=D.%20W.+Sims&title=Four+steps+to+curb+%E2%80%98ocean+roadkill.%E2%80%99&publication_year=2023&journal=Nature&volume=621&pages=34-38)

## Web resources

Protecting Blue Corridors Initiative: <https://bluecorridors.org>

World Shipping Council Whale Chart: <https://www.worldshipping.org/whales>

Blue Whales Blue Skies: <https://bluewhalesblueskies.org/>

Sustainable Shipping Initiative: <https://sustainableshipping.org/>

Whale Safe: <https://whalesafe.com/>

------------------------------------------------------------------------

## Image credits

| Photographer | Platform / organisation | Slide(s) |
|----|----|----|
| Flavio | Unsplash | "Why do whales matter?" and "Whales are important to people and the planet" section slides |
| Jorge Vasconez | Unsplash | "Why do whales matter?" and "The value of a whale" |
| Martha Holmes | naturepl.com / WWF | "In the Arctic context" |
| Paul Nicklen | WWF-Canada | Narwhal images: Arctic whales, potential shipping impacts, "Arctic whales face the simultaneous pressures…" |
| David Merron | WWF-US | Beluga: Arctic whales; Mitigation slides |
| VDOS Global | WWF-Canada | Bowhead whales (Arctic whales slide) |
| Doug Allen | WWF-US | Closing slide (belugas) |
| Boris Horvat | AFP via Getty | "Four actions to curb 'ocean roadkill'" |

------------------------------------------------------------------------
